export const APP_LOAD = 'APP_LOAD';
export const REQUEST_EMPLOYES_STARTED = 'REQUEST_EMPLOYES_STARTED';
export const REQUEST_EMPLOYES_SUCCESS = 'REQUEST_EMPLOYES_SUCCESS';
export const REQUEST_EMPLOYES_FAILURE = 'REQUEST_EMPLOYES_FAILURE';

export const ADD_EMPLOYE = 'ADD_EMPLOYE';
export const ADD_EMPLOYE_STARTED = 'ADD_EMPLOYE_STARTED';
export const ADD_EMPLOYE_SUCCESS = 'ADD_EMPLOYE_SUCCESS';
export const ADD_EMPLOYE_FAILURE = 'ADD_EMPLOYE_FAILURE';

export const UPDATE_EMPLOYE = 'UPDATE_EMPLOYE';
export const UPDATE_EMPLOYE_STARTED = 'UPDATE_EMPLOYE_STARTED';
export const UPDATE_EMPLOYE_SUCCESS = 'UPDATE_EMPLOYE_SUCCESS';
export const UPDATE_EMPLOYE_FAILURE = 'UPDATE_EMPLOYE_FAILURE';

export const DELETE_EMPLOYE = 'DELETE_EMPLOYE';
export const DELETE_EMPLOYE_STARTED = 'DELETE_EMPLOYE_STARTED';
export const DELETE_EMPLOYE_SUCCESS = 'DELETE_EMPLOYE_SUCCESS';
export const DELETE_EMPLOYE_FAILURE = 'DELETE_EMPLOYE_FAILURE';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

